### ISSUE TITLE
Make tree_magic an optional dependency, allow custom mime header

### ISSUE THREAD

**Issue by alexwennerberg** [gemrest/windmark#1]
Right now, it appears that tree_magic is only used when sending a file. I would argue that it would make more sense to allow the user of this library to set the filetype header on their own, and use whatever method they like to determine that (e.g. file extension, data guessing, some combination of the two) rather than couple it with this function

Thanks for this library!

**Comment by Fuwn** [comment]
Fair enough. I'll look into making it optional sometime this week.

**Comment by Fuwn** [comment]
Should be implemented with commit https://github.com/gemrest/windmark/commit/40647bc49a581eaa6b3a38b53c6c03402ca7b628 and [crates.io](https://crates.io) version [`0.1.6`](https://crates.io/crates/windmark/0.1.6)!

**Comment by Fuwn** [comment]
Any updates? or should I consider this solved?
