### ISSUE TITLE
Windmark on Cloudron - One click Deployment

### ISSUE THREAD

**Issue by OrcVole** [gemrest/windmark#2]
It would be nice if all the complexity were removed by letting people deploy their own Windmark gemini server with just one click.

If you could create a Docker image for Windmark, it would be the bulk of the work.

A discussion has been started on the Cloudron Forum:
https://forum.cloudron.io/topic/8166/windmark-on-cloudron-gemini-protocol-server

Cloudron has a demo of how you can deploy applications on the main website:  
https://cloudron.io

**Comment by Fuwn** [comment]
Windmark is crate for making Gemini capsules, not a Gemini capsule itself. There is no way to "deploy" Windmark.
